version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app/backend
      - /usr/app/backend/node_modules
    env_file: .env.docker
    ports:
      - '5050:5050'
    depends_on:
      - postgres
    networks:
      - default
  postgres:
    image: postgres:14.1-alpine
    ports:
      - '5433:5432' # Map host port 5433 to container port 5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root # Match the password with DATABASE_PASSWORD
      POSTGRES_USER: postgres # Match the user with DATABASE_USERNAME
      POSTGRES_DB: nest_discussion_forum # Match the database name with DATABASE_NAME
    networks:
      - default
volumes:
  db:
    driver: local
networks:
  default:
    driver: bridge
